#!/bin/bash -e
set -e -u

HUGO_VERSION=0.16
DOWNLOAD_FILE_NAME=hugo_${HUGO_VERSION}_linux-64bit.tgz
export IMAGE_TAG=pamrucinque/hugo

docker build --pull \
  --build-arg HUGO_VERSION=${HUGO_VERSION} \
  --build-arg DOWNLOAD_FILE_NAME=${DOWNLOAD_FILE_NAME} \
  -t ${IMAGE_TAG} .
